[manta] [ready for review] manta client
Manta-Network/manta-subxt pull request #2
Opened 2021-05-12 14:04 UTC by zhenfeizhang

2021-05-12 18:04 UTC, stechu requested changes
Thanks for the PR, this is tons of work!
In general, remove all the dead-code across the files. Also, I highly suggest to have a consistent naming with `pallet-manta-pay`, maybe it is the right time to write a `pallet-manta-pay` API spec.

2021-05-12 18:04 UTC, stechu commented on src/extrinsic/manta_pay.rs
> +    async fn init_asset(
Can we have consistent naming with `pallet-manta-pay`, I think init_asset is a better name than `init` though.

2021-05-12 18:04 UTC, stechu commented on src/extrinsic/manta_pay.rs
> +    async fn mint_token(
Also, can we have consistent naming for token/asset?

2021-05-12 18:14 UTC, zhenfeizhang commented on examples/manta_transfer.rs
> +// async fn main() -> Result<(), Box<dyn std::error::Error>> {
yeah... those example... I am working on making them working... so they will be uncommented..

2021-05-12 18:33 UTC, zhenfeizhang commented on src/extrinsic/manta_pay.rs
> +    async fn init_asset(
okay. still with `init_asset` here. will update `pallet-manta-pay`

2021-05-12 18:33 UTC, zhenfeizhang commented on src/extrinsic/manta_pay.rs
> +    async fn mint_token(
lets use `asset`...

2021-05-12 20:03 UTC, zhenfeizhang commented on examples/manta_transfer.rs
> +// async fn main() -> Result<(), Box<dyn std::error::Error>> {
examples re-enabled

2021-05-17 03:49 UTC, stechu approved these changes

2021-05-17 03:50 UTC, merged